### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by dacb** [cmcalli716/flashing_lights#1]
See if you can do a little cleanup of your repository.  I see an `environment.yml` like file in the `env` directory of the module directory.  These are typically stored in the root of the repository.  Also, your tech review PDF should be in the `doc` directory.  I will write a separate issue for improving your design documents.

I only saw one branch with any real code.  Maybe that is an oversight on my part, but make sure you are using version control and committing and pushing your code regularly.

**Comment by cmcalli716** [comment]
@dacb we have done some pretty heavy revisions to the repo structure; is there any more work we need to do for the organization or am I good to close this issue?
